Add a strict keyword argument to chunked()
more-itertools/more-itertools pull request #463
Opened 2020-09-15 06:26 UTC by shlomif

See:

https://github.com/more-itertools/more-itertools/issues/461

issue#461 . It raises an exception if there's a smaller chunk at
the end.

Tested using tox with python 3.8, but may have some rough edges.
Comments are welcome.

2020-09-15 08:03 UTC, pylang commented
Looks good.  I would truncate the exception in the docstring to the most critical parts.

2020-09-15 09:41 UTC, shlomif commented
On Tue, 15 Sep 2020 01:03:45 -0700
pylang <notifications@github.com> wrote:

> Looks good.  I would truncate the exception in the docstring to the most
> critical parts.
> 

Thanks @pylang ! I added and pushed two new commits with some cleanups,
including for your input.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/

Chuck Norris wrote an interpreter for a Turing-complete language using only
NOPs.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

2020-09-15 10:55 UTC, jtwool requested changes
Some nits about the documentation. I like the use of the word "divisible" here. Good work.

2020-09-15 10:55 UTC, jtwool commented on more_itertools/more.py
> +    If this is the case and *strict* is True, then :func:`chunked` will
Maybe change this to:
"If `strict=True`, `chunked` raises a `ValueError` if `iterable` is not divisible by `n`."

2020-09-15 10:55 UTC, jtwool commented on more_itertools/more.py
> +                    raise ValueError('There are fewer items in the last chunk!')
Suggested error:

`ValueError("Iterable is not divisible by n")`

2020-09-16 01:01 UTC, bbayles requested changes
Thanks for the PR. Some changes and a question before we merge.

2020-09-16 01:01 UTC, bbayles commented on more_itertools/more.py
> +        return iter(ret(iterator))
Any particular reason to return this, instead of just getting rid of the function definition and doing `yield chunk`?

2020-09-16 01:01 UTC, bbayles commented on more_itertools/more.py
> +    raise an exception.
```suggestion
    raise an ``ValueError``.
```

2020-09-16 01:01 UTC, bbayles commented on more_itertools/more.py
> +        list(chunked([1, 2, 3, 4, 5, 6, 7, 8], 3, strict=True))
I think this needs `>>>` in front like the other code blocks. Also possibly the `IGNORE_EXCEPTION_DETAIL` [directive].

2020-09-16 19:09 UTC, bbayles commented on more_itertools/more.py
> +    If *strict* is True, then :func:`chunked` raises a `ValueError`.
I think we lost the "if not divisible" part here, ha.

2020-09-16 19:10 UTC, bbayles commented on more_itertools/more.py
> -    return takewhile(len, (seq[i : i + n] for i in count(0, n)))
Could we make this match the pattern in `chunked`? If `strict` is `False`, do nothing different. Otherwise, do the extra checking.

2020-09-16 19:29 UTC, bbayles commented
Also: we'll need to update the type stubs. I'm not sure why GitHub Actions didn't run to tell us this.

2020-09-17 20:38 UTC, shlomif commented
@bbayles : thanks for the comments - i revised the code but now the CI is failing (and sorry it took me so long).

2020-09-18 08:36 UTC, shlomif commented
Hi all! After I do `pip3 install --user --upgrade mypy` followed by `stubtest more_itertools.more more_itertools.recipes` I am getting no errors on mageia8 and many unrelated errors on fedora 32. I'll try building cpython3 from source next.

2020-09-18 15:47 UTC, shlomif commented
The CI checks seem to be passing now. Please let me know if there is anything else you need. Shanah Tovah!

2020-09-18 15:52 UTC, bbayles commented
Thanks; I'll merge this soon. Shanah Tovah!

2020-09-19 07:53 UTC, shlomif commented
On Fri, 18 Sep 2020 08:52:31 -0700
Bo Bayles <notifications@github.com> wrote:

> Thanks; I'll merge this soon. Shanah Tovah!
> 

You're welcome, and thanks! Shanah Tovah!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://github.com/shlomif/what-you-should-know-about-automated-testing

Chuck Norris is the reason why OpenBSD is called OpenBSD. They wanted to
call it LockedDownBSD but couldn't find a way to keep Chuck Norris out!
(By Andrew Brehm) — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

2020-09-19 14:30 UTC, bbayles approved these changes

2020-09-19 17:20 UTC, merged

2020-09-19 17:39 UTC, shlomif commented
On Sat, 19 Sep 2020 10:20:52 -0700
Bo Bayles <notifications@github.com> wrote:

> Merged #463 into master.
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
“So, who the hell is Qoheleth?” - https://shlom.in/qoheleth

“A is A, and A is not not-A? WTH is he talking about??! Of course A can be
not-A! I want a little of the stuff he’s on!”
    — Initial reaction to the https://en.wikipedia.org/wiki/Organon

Please reply to list if it's a mailing list post - https://shlom.in/reply .

2020-09-24 16:48 UTC, cool-RR commented on more_itertools/more.py
> +                    raise ValueError("seq is not divisible by n.")
@bbayles @shlomif 
Wouldn't this raise the exception only after you've consumed the entire iterator? Don't you think it should raise it when calling the function?

2020-09-24 16:50 UTC, cool-RR commented
Good job @shlomif and @jtwool !