documentation and tests for multiple exceptions in `iter_expect`
more-itertools/more-itertools pull request #550
Opened 2021-09-01 20:58 UTC by MarcinKonowalczyk

Added documentation and test in response to #541. Also updated the typing of `iter_except`.

2021-09-03 00:53 UTC, bbayles requested changes
Nitpick for the docstring

2021-09-03 00:53 UTC, bbayles commented on more_itertools/recipes.py
> +        >>> l = [1,2,3,'...',4,5,6]
Could you format the list like `black` would?

2021-09-05 19:36 UTC, MarcinKonowalczyk commented
I've responded to the formatting request. Anything else to do on this?

2021-09-10 11:35 UTC, bbayles approved these changes

2021-09-10 11:35 UTC, merged