Introduce starstarmap
more-itertools/more-itertools pull request #680
Opened 2023-02-25 19:22 UTC by Skeen

### Issue reference
Closes #679

### Changes
Introduces `starstarmap`

2023-02-25 20:58 UTC, DamianB-BitFlipper commented
Just to give my 2 cents as a complete outsider, before I read up on the issue, I though that this function mapped and applied the arguments 2 layers deep.

Something akin to iterating `[(1, 2), (3, 4)], [(5, 6, 7), (8,)]` as `fn(1, 2, 3, 4), fn(5, 6, 7, 8)`, if that makes sense.

After reading the issue, it makes total sense.

It seems that Python nomenclature calls the `**` a "double star". I do not know if it will make the code more clear if it were `doublestarmap`. I am still iffy on this naming even.

2023-02-25 23:45 UTC, Skeen commented
I'm very open to renaming it `doublestarmap`. I have no strong attachment to the `starstarmap` name.

@bbayles What do you think?

2023-03-10 12:59 UTC, Skeen commented on more_itertools/more.py
> +def starstarmap(function, iterable):
Done!

2023-04-28 18:30 UTC, ergoithz requested changes
In case you didn't noticed, CI is complaining about your PR containing PEP8 violations, you'll have a higher chance of getting this PR approved after solving them. I annotated where those issues are coming from, hoping it helps.

2023-04-28 18:30 UTC, ergoithz commented on tests/test_more.py
> +        iterable = [1,2,3,4]
pep8 violation: add space after `,`

2023-04-28 18:30 UTC, ergoithz commented on more_itertools/more.py
pep8 violation: use two empty lines between module-level functions

2023-11-05 13:59 UTC, closed without merging